export * from "./Hero";
export * from "./HeroSlider"
export * from "./EverythingYouNeed";
export * from "./CompleteStudent"
export * from "./WhyChooseCe"
export * from "./ReadyToTransform"
export * from "./AboutUs";
export * from "./ProblemStatement";
export * from "./Solution"; 
export * from "./PaymentPlan"